version: '3'
services:
  redis-server:
    image: redis
  scrapper:
    image: davidgeismar/artifacts-scrapper:latest
    environment:
      - REDIS_URL=redis://redis-server:6379/0
      - DATABASE_PASSWORD=0FxpAtQ3qnspyG8CXTdN
      - DATABASE_USERNAME=postgres
      - DATABASE_URL=database-1.cavouzs9axwu.eu-west-2.rds.amazonaws.com:5432
      - ARTIFACTS_ENV=docker_production
