version: '3'
services:
  redis-server:
    image: redis
    restart: always
  scrapper:
    image: davidgeismar/artifacts-scrapper:without-db
    command: "bundle exec rake scrap_sources:scrap\"[['christies'],nil,[2019]]\""
    volumes:
      - ./logs/artifacts_scrapper:/usr/src/artifacts_scrapper/log
    environment:
      - REDIS_URL=redis://redis-server:6379/0
      - ARTIFACTS_ENV=docker_development
      - DATA_API_BASE=http://data_api:3000
    depends_on:
      - data_api
      - redis-server
  data_api:
    volumes:
      - ./logs/artifacts_data_api:/artifacts_data_api/log
    build: ./
    entrypoint: ./entrypoint.sh
    command: 'rails server -b 0.0.0.0'
    environment:
      - RAILS_ENV=docker_development
      - SECRET_KEY_BASE=docker_development_secret
  sidekiq:
    volumes:
      - ./logs/sidekiq/scrapper:/usr/src/artifacts_scrapper/log
    image: davidgeismar/artifacts-scrapper:without-db
    command: 'bundle exec sidekiq -r ./artifacts_scrapper.rb 2>&1 | tee ./log/sidekiq.log'
    environment:
      - REDIS_URL=redis://redis-server:6379/0
      - ARTIFACTS_ENV=docker_development
      - DATA_API_BASE=http://data_api:3000
    depends_on:
      - redis-server
      - data_api
