# file that builds the current service onkly
version: '3'
services:
  data_api:
    volumes:
      - ./logs/artifacts_data_api:/artifacts_data_api/log
    build: ./
    entrypoint: ./entrypoint.sh
    command: 'rails server -b 0.0.0.0'
    environment:
      - RAILS_ENV=production
      - SECRET_KEY_BASE=production_secret
      - DB_PASSWORD=artifacts
      - DB_USERNAME=postgres
      - DB_URL=artifacts-test.cndqyekjgsit.eu-west-3.rds.amazonaws.com
      - DB_PORT=5432
      - DB_NAME=artifacts-test
